# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: application.proto for package ''

require 'grpc'
require_relative 'application_pb'

module RubyInterface
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'rubyInterface'

    rpc :getHero, HeroID, Hero
  end

  Stub = Service.rpc_stub_class
end
module PythonInterface
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'pythonInterface'

    rpc :generateMonster, MonsterId, Monster
  end

  Stub = Service.rpc_stub_class
end
module JavaInterface
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'javaInterface'

    rpc :calculateCombat, Combat, Combat
    rpc :rollDice, DiceType, Dice
  end

  Stub = Service.rpc_stub_class
end
