# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/Combat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages/Combat.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15messages/Combat.proto\"\x99\x01\n\x06\x43ombat\x12\x14\n\x0c\x61tk_strength\x18\x01 \x01(\x05\x12\x16\n\x0e\x64\x65\x66_resistance\x18\x02 \x01(\x05\x12\x12\n\ndef_health\x18\x03 \x01(\x05\x12\x1f\n\x07who_won\x18\x04 \x01(\x0e\x32\x0e.Combat.winner\",\n\x06winner\x12\x08\n\x04none\x10\x00\x12\n\n\x06player\x10\x01\x12\x0c\n\x08\x63reature\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_COMBAT_WINNER = _descriptor.EnumDescriptor(
  name='winner',
  full_name='Combat.winner',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='none', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='player', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='creature', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=135,
  serialized_end=179,
)
_sym_db.RegisterEnumDescriptor(_COMBAT_WINNER)


_COMBAT = _descriptor.Descriptor(
  name='Combat',
  full_name='Combat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='atk_strength', full_name='Combat.atk_strength', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='def_resistance', full_name='Combat.def_resistance', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='def_health', full_name='Combat.def_health', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='who_won', full_name='Combat.who_won', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMBAT_WINNER,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=179,
)

_COMBAT.fields_by_name['who_won'].enum_type = _COMBAT_WINNER
_COMBAT_WINNER.containing_type = _COMBAT
DESCRIPTOR.message_types_by_name['Combat'] = _COMBAT

Combat = _reflection.GeneratedProtocolMessageType('Combat', (_message.Message,), dict(
  DESCRIPTOR = _COMBAT,
  __module__ = 'messages.Combat_pb2'
  # @@protoc_insertion_point(class_scope:Combat)
  ))
_sym_db.RegisterMessage(Combat)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
