# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/Combat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from messages import Hero_pb2 as messages_dot_Hero__pb2
from messages import Monster_pb2 as messages_dot_Monster__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages/Combat.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15messages/Combat.proto\x1a\x13messages/Hero.proto\x1a\x16messages/Monster.proto\"\x9a\x01\n\x06\x43ombat\x12\x14\n\x05\x61Hero\x18\x01 \x01(\x0b\x32\x05.Hero\x12\x1a\n\x08\x61Monster\x18\x02 \x01(\x0b\x32\x08.Monster\x12%\n\x0bwho_attacks\x18\x03 \x01(\x0e\x32\x10.Combat.attacker\x12\x14\n\x0c\x64\x65\x61\x64\x44\x65\x66\x65nder\x18\x04 \x01(\x08\"!\n\x08\x61ttacker\x12\x08\n\x04hero\x10\x00\x12\x0b\n\x07monster\x10\x01\x62\x06proto3')
  ,
  dependencies=[messages_dot_Hero__pb2.DESCRIPTOR,messages_dot_Monster__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_COMBAT_ATTACKER = _descriptor.EnumDescriptor(
  name='attacker',
  full_name='Combat.attacker',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='hero', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='monster', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=192,
  serialized_end=225,
)
_sym_db.RegisterEnumDescriptor(_COMBAT_ATTACKER)


_COMBAT = _descriptor.Descriptor(
  name='Combat',
  full_name='Combat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aHero', full_name='Combat.aHero', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aMonster', full_name='Combat.aMonster', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='who_attacks', full_name='Combat.who_attacks', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deadDefender', full_name='Combat.deadDefender', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMBAT_ATTACKER,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=225,
)

_COMBAT.fields_by_name['aHero'].message_type = messages_dot_Hero__pb2._HERO
_COMBAT.fields_by_name['aMonster'].message_type = messages_dot_Monster__pb2._MONSTER
_COMBAT.fields_by_name['who_attacks'].enum_type = _COMBAT_ATTACKER
_COMBAT_ATTACKER.containing_type = _COMBAT
DESCRIPTOR.message_types_by_name['Combat'] = _COMBAT

Combat = _reflection.GeneratedProtocolMessageType('Combat', (_message.Message,), dict(
  DESCRIPTOR = _COMBAT,
  __module__ = 'messages.Combat_pb2'
  # @@protoc_insertion_point(class_scope:Combat)
  ))
_sym_db.RegisterMessage(Combat)


# @@protoc_insertion_point(module_scope)
