# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/Dice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages/Dice.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13messages/Dice.proto\"5\n\x04\x44ice\x12\x14\n\x0crolledNumber\x18\x01 \x01(\x05\x12\x17\n\x04type\x18\x02 \x01(\x0b\x32\t.DiceType\"q\n\x08\x44iceType\x12 \n\x08tipoDado\x18\x01 \x01(\x0e\x32\x0e.DiceType.Type\"C\n\x04Type\x12\x06\n\x02\x44\x34\x10\x00\x12\x06\n\x02\x44\x36\x10\x01\x12\x06\n\x02\x44\x38\x10\x02\x12\x07\n\x03\x44\x31\x30\x10\x03\x12\x07\n\x03\x44\x31\x32\x10\x04\x12\x07\n\x03\x44\x32\x30\x10\x05\x12\x08\n\x04\x44\x31\x30\x30\x10\x06\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DICETYPE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='DiceType.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='D4', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D6', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D8', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D10', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D12', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D20', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D100', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=124,
  serialized_end=191,
)
_sym_db.RegisterEnumDescriptor(_DICETYPE_TYPE)


_DICE = _descriptor.Descriptor(
  name='Dice',
  full_name='Dice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rolledNumber', full_name='Dice.rolledNumber', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Dice.type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=76,
)


_DICETYPE = _descriptor.Descriptor(
  name='DiceType',
  full_name='DiceType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tipoDado', full_name='DiceType.tipoDado', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DICETYPE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=191,
)

_DICE.fields_by_name['type'].message_type = _DICETYPE
_DICETYPE.fields_by_name['tipoDado'].enum_type = _DICETYPE_TYPE
_DICETYPE_TYPE.containing_type = _DICETYPE
DESCRIPTOR.message_types_by_name['Dice'] = _DICE
DESCRIPTOR.message_types_by_name['DiceType'] = _DICETYPE

Dice = _reflection.GeneratedProtocolMessageType('Dice', (_message.Message,), dict(
  DESCRIPTOR = _DICE,
  __module__ = 'messages.Dice_pb2'
  # @@protoc_insertion_point(class_scope:Dice)
  ))
_sym_db.RegisterMessage(Dice)

DiceType = _reflection.GeneratedProtocolMessageType('DiceType', (_message.Message,), dict(
  DESCRIPTOR = _DICETYPE,
  __module__ = 'messages.Dice_pb2'
  # @@protoc_insertion_point(class_scope:DiceType)
  ))
_sym_db.RegisterMessage(DiceType)


# @@protoc_insertion_point(module_scope)
