# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/Monster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages/Monster.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16messages/Monster.proto\"Y\n\x07Monster\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08strength\x18\x03 \x01(\x05\x12\x12\n\nresistance\x18\x04 \x01(\x05\x12\x0e\n\x06health\x18\x05 \x01(\x05\"\x17\n\tMonsterQt\x12\n\n\x02qt\x18\x01 \x01(\x05\"%\n\x08Monsters\x12\x19\n\x07monster\x18\x01 \x03(\x0b\x32\x08.Monsterb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MONSTER = _descriptor.Descriptor(
  name='Monster',
  full_name='Monster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Monster.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Monster.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strength', full_name='Monster.strength', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resistance', full_name='Monster.resistance', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='health', full_name='Monster.health', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=115,
)


_MONSTERQT = _descriptor.Descriptor(
  name='MonsterQt',
  full_name='MonsterQt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qt', full_name='MonsterQt.qt', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=140,
)


_MONSTERS = _descriptor.Descriptor(
  name='Monsters',
  full_name='Monsters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='monster', full_name='Monsters.monster', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=179,
)

_MONSTERS.fields_by_name['monster'].message_type = _MONSTER
DESCRIPTOR.message_types_by_name['Monster'] = _MONSTER
DESCRIPTOR.message_types_by_name['MonsterQt'] = _MONSTERQT
DESCRIPTOR.message_types_by_name['Monsters'] = _MONSTERS

Monster = _reflection.GeneratedProtocolMessageType('Monster', (_message.Message,), dict(
  DESCRIPTOR = _MONSTER,
  __module__ = 'messages.Monster_pb2'
  # @@protoc_insertion_point(class_scope:Monster)
  ))
_sym_db.RegisterMessage(Monster)

MonsterQt = _reflection.GeneratedProtocolMessageType('MonsterQt', (_message.Message,), dict(
  DESCRIPTOR = _MONSTERQT,
  __module__ = 'messages.Monster_pb2'
  # @@protoc_insertion_point(class_scope:MonsterQt)
  ))
_sym_db.RegisterMessage(MonsterQt)

Monsters = _reflection.GeneratedProtocolMessageType('Monsters', (_message.Message,), dict(
  DESCRIPTOR = _MONSTERS,
  __module__ = 'messages.Monster_pb2'
  # @@protoc_insertion_point(class_scope:Monsters)
  ))
_sym_db.RegisterMessage(Monsters)


# @@protoc_insertion_point(module_scope)
