# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application.proto

require 'google/protobuf'

require_relative 'Hero_pb'
require_relative 'Combat_pb'
require_relative 'Dice_pb'
require_relative 'Monster_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end
