# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application.proto

require 'google/protobuf'

require_relative 'messages/Hero_pb'
require_relative 'messages/Combat_pb'
require_relative 'messages/Dice_pb'
require_relative 'messages/Monster_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end
