# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/Combat.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Combat" do
    optional :atk_strength, :int32, 1
    optional :atk_resistance, :int32, 2
    optional :atk_health, :int32, 3
    optional :def_strength, :int32, 4
    optional :def_resistance, :int32, 5
    optional :def_health, :int32, 6
    optional :who_won, :enum, 7, "Combat.winner"
  end
  add_enum "Combat.winner" do
    value :Defender, 0
    value :Attacker, 1
  end
end

Combat = Google::Protobuf::DescriptorPool.generated_pool.lookup("Combat").msgclass
Combat::Winner = Google::Protobuf::DescriptorPool.generated_pool.lookup("Combat.winner").enummodule
