# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/Combat.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Combat" do
    optional :atk_strength, :int32, 1
    optional :def_resistance, :int32, 2
    optional :def_health, :int32, 3
    optional :who_won, :enum, 4, "Combat.winner"
  end
  add_enum "Combat.winner" do
    value :None, 0
    value :Player, 1
    value :Creature, 2
  end
end

Combat = Google::Protobuf::DescriptorPool.generated_pool.lookup("Combat").msgclass
Combat::Winner = Google::Protobuf::DescriptorPool.generated_pool.lookup("Combat.winner").enummodule
