# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/Combat.proto

require 'google/protobuf'

require_relative 'Hero_pb'
require_relative 'Monster_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Combat" do
    optional :aHero, :message, 1, "Hero"
    optional :aMonster, :message, 2, "Monster"
    optional :who_attacks, :enum, 3, "Combat.attacker"
    optional :deadDefender, :bool, 4
  end
  add_enum "Combat.attacker" do
    value :hero, 0
    value :monster, 1
  end
end

Combat = Google::Protobuf::DescriptorPool.generated_pool.lookup("Combat").msgclass
Combat::Attacker = Google::Protobuf::DescriptorPool.generated_pool.lookup("Combat.attacker").enummodule
