# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/Dice.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Dice" do
    optional :rolledNumber, :int32, 1
    optional :type, :message, 2, "DiceType"
  end
  add_message "DiceType" do
  end
  add_enum "DiceType.Type" do
    value :D4, 0
    value :D6, 1
    value :D8, 2
    value :D10, 3
    value :D12, 4
    value :D20, 5
    value :D100, 6
  end
end

Dice = Google::Protobuf::DescriptorPool.generated_pool.lookup("Dice").msgclass
DiceType = Google::Protobuf::DescriptorPool.generated_pool.lookup("DiceType").msgclass
DiceType::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("DiceType.Type").enummodule
