# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/Hero.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Hero" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :strength, :int32, 3
    optional :resistance, :int32, 4
    optional :health, :int32, 5
  end
  add_message "HeroID" do
    optional :id, :int32, 1
  end
end

Hero = Google::Protobuf::DescriptorPool.generated_pool.lookup("Hero").msgclass
HeroID = Google::Protobuf::DescriptorPool.generated_pool.lookup("HeroID").msgclass
