# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/Monster.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Monster" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :strength, :int32, 3
    optional :resistance, :int32, 4
    optional :health, :int32, 5
  end
  add_message "MonsterId" do
    optional :id, :int32, 1
  end
end

Monster = Google::Protobuf::DescriptorPool.generated_pool.lookup("Monster").msgclass
MonsterId = Google::Protobuf::DescriptorPool.generated_pool.lookup("MonsterId").msgclass
