package main.messages;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/Dice.proto

public final class DiceOuterClass {
  private DiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Dice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 rolledNumber = 1;</code>
     */
    int getRolledNumber();

    /**
     * <code>.DiceType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>.DiceType type = 2;</code>
     */
    DiceOuterClass.DiceType getType();
    /**
     * <code>.DiceType type = 2;</code>
     */
    DiceOuterClass.DiceTypeOrBuilder getTypeOrBuilder();
  }
  /**
   * Protobuf type {@code Dice}
   */
  public  static final class Dice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Dice)
      DiceOrBuilder {
    // Use Dice.newBuilder() to construct.
    private Dice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dice() {
      rolledNumber_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Dice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              rolledNumber_ = input.readInt32();
              break;
            }
            case 18: {
              DiceOuterClass.DiceType.Builder subBuilder = null;
              if (type_ != null) {
                subBuilder = type_.toBuilder();
              }
              type_ = input.readMessage(DiceOuterClass.DiceType.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(type_);
                type_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DiceOuterClass.internal_static_Dice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DiceOuterClass.internal_static_Dice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DiceOuterClass.Dice.class, DiceOuterClass.Dice.Builder.class);
    }

    public static final int ROLLEDNUMBER_FIELD_NUMBER = 1;
    private int rolledNumber_;
    /**
     * <code>int32 rolledNumber = 1;</code>
     */
    public int getRolledNumber() {
      return rolledNumber_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private DiceOuterClass.DiceType type_;
    /**
     * <code>.DiceType type = 2;</code>
     */
    public boolean hasType() {
      return type_ != null;
    }
    /**
     * <code>.DiceType type = 2;</code>
     */
    public DiceOuterClass.DiceType getType() {
      return type_ == null ? DiceOuterClass.DiceType.getDefaultInstance() : type_;
    }
    /**
     * <code>.DiceType type = 2;</code>
     */
    public DiceOuterClass.DiceTypeOrBuilder getTypeOrBuilder() {
      return getType();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rolledNumber_ != 0) {
        output.writeInt32(1, rolledNumber_);
      }
      if (type_ != null) {
        output.writeMessage(2, getType());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rolledNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rolledNumber_);
      }
      if (type_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getType());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DiceOuterClass.Dice)) {
        return super.equals(obj);
      }
      DiceOuterClass.Dice other = (DiceOuterClass.Dice) obj;

      boolean result = true;
      result = result && (getRolledNumber()
          == other.getRolledNumber());
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && getType()
            .equals(other.getType());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROLLEDNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getRolledNumber();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DiceOuterClass.Dice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DiceOuterClass.Dice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DiceOuterClass.Dice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DiceOuterClass.Dice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DiceOuterClass.Dice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DiceOuterClass.Dice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DiceOuterClass.Dice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DiceOuterClass.Dice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DiceOuterClass.Dice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DiceOuterClass.Dice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DiceOuterClass.Dice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Dice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Dice)
        DiceOuterClass.DiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DiceOuterClass.internal_static_Dice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DiceOuterClass.internal_static_Dice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DiceOuterClass.Dice.class, DiceOuterClass.Dice.Builder.class);
      }

      // Construct using DiceOuterClass.Dice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rolledNumber_ = 0;

        if (typeBuilder_ == null) {
          type_ = null;
        } else {
          type_ = null;
          typeBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DiceOuterClass.internal_static_Dice_descriptor;
      }

      public DiceOuterClass.Dice getDefaultInstanceForType() {
        return DiceOuterClass.Dice.getDefaultInstance();
      }

      public DiceOuterClass.Dice build() {
        DiceOuterClass.Dice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DiceOuterClass.Dice buildPartial() {
        DiceOuterClass.Dice result = new DiceOuterClass.Dice(this);
        result.rolledNumber_ = rolledNumber_;
        if (typeBuilder_ == null) {
          result.type_ = type_;
        } else {
          result.type_ = typeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DiceOuterClass.Dice) {
          return mergeFrom((DiceOuterClass.Dice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DiceOuterClass.Dice other) {
        if (other == DiceOuterClass.Dice.getDefaultInstance()) return this;
        if (other.getRolledNumber() != 0) {
          setRolledNumber(other.getRolledNumber());
        }
        if (other.hasType()) {
          mergeType(other.getType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DiceOuterClass.Dice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DiceOuterClass.Dice) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int rolledNumber_ ;
      /**
       * <code>int32 rolledNumber = 1;</code>
       */
      public int getRolledNumber() {
        return rolledNumber_;
      }
      /**
       * <code>int32 rolledNumber = 1;</code>
       */
      public Builder setRolledNumber(int value) {
        
        rolledNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rolledNumber = 1;</code>
       */
      public Builder clearRolledNumber() {
        
        rolledNumber_ = 0;
        onChanged();
        return this;
      }

      private DiceOuterClass.DiceType type_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          DiceOuterClass.DiceType, DiceOuterClass.DiceType.Builder, DiceOuterClass.DiceTypeOrBuilder> typeBuilder_;
      /**
       * <code>.DiceType type = 2;</code>
       */
      public boolean hasType() {
        return typeBuilder_ != null || type_ != null;
      }
      /**
       * <code>.DiceType type = 2;</code>
       */
      public DiceOuterClass.DiceType getType() {
        if (typeBuilder_ == null) {
          return type_ == null ? DiceOuterClass.DiceType.getDefaultInstance() : type_;
        } else {
          return typeBuilder_.getMessage();
        }
      }
      /**
       * <code>.DiceType type = 2;</code>
       */
      public Builder setType(DiceOuterClass.DiceType value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          typeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.DiceType type = 2;</code>
       */
      public Builder setType(
          DiceOuterClass.DiceType.Builder builderForValue) {
        if (typeBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          typeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.DiceType type = 2;</code>
       */
      public Builder mergeType(DiceOuterClass.DiceType value) {
        if (typeBuilder_ == null) {
          if (type_ != null) {
            type_ =
              DiceOuterClass.DiceType.newBuilder(type_).mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          typeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.DiceType type = 2;</code>
       */
      public Builder clearType() {
        if (typeBuilder_ == null) {
          type_ = null;
          onChanged();
        } else {
          type_ = null;
          typeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.DiceType type = 2;</code>
       */
      public DiceOuterClass.DiceType.Builder getTypeBuilder() {
        
        onChanged();
        return getTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>.DiceType type = 2;</code>
       */
      public DiceOuterClass.DiceTypeOrBuilder getTypeOrBuilder() {
        if (typeBuilder_ != null) {
          return typeBuilder_.getMessageOrBuilder();
        } else {
          return type_ == null ?
              DiceOuterClass.DiceType.getDefaultInstance() : type_;
        }
      }
      /**
       * <code>.DiceType type = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          DiceOuterClass.DiceType, DiceOuterClass.DiceType.Builder, DiceOuterClass.DiceTypeOrBuilder> 
          getTypeFieldBuilder() {
        if (typeBuilder_ == null) {
          typeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              DiceOuterClass.DiceType, DiceOuterClass.DiceType.Builder, DiceOuterClass.DiceTypeOrBuilder>(
                  getType(),
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        return typeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Dice)
    }

    // @@protoc_insertion_point(class_scope:Dice)
    private static final DiceOuterClass.Dice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DiceOuterClass.Dice();
    }

    public static DiceOuterClass.Dice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Dice>
        PARSER = new com.google.protobuf.AbstractParser<Dice>() {
      public Dice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Dice(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dice> getParserForType() {
      return PARSER;
    }

    public DiceOuterClass.Dice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DiceTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DiceType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.DiceType.Type tipoDado = 1;</code>
     */
    int getTipoDadoValue();
    /**
     * <code>.DiceType.Type tipoDado = 1;</code>
     */
    DiceOuterClass.DiceType.Type getTipoDado();
  }
  /**
   * Protobuf type {@code DiceType}
   */
  public  static final class DiceType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DiceType)
      DiceTypeOrBuilder {
    // Use DiceType.newBuilder() to construct.
    private DiceType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DiceType() {
      tipoDado_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DiceType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              tipoDado_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DiceOuterClass.internal_static_DiceType_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DiceOuterClass.internal_static_DiceType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DiceOuterClass.DiceType.class, DiceOuterClass.DiceType.Builder.class);
    }

    /**
     * Protobuf enum {@code DiceType.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>D4 = 0;</code>
       */
      D4(0),
      /**
       * <code>D6 = 1;</code>
       */
      D6(1),
      /**
       * <code>D8 = 2;</code>
       */
      D8(2),
      /**
       * <code>D10 = 3;</code>
       */
      D10(3),
      /**
       * <code>D12 = 4;</code>
       */
      D12(4),
      /**
       * <code>D20 = 5;</code>
       */
      D20(5),
      /**
       * <code>D100 = 6;</code>
       */
      D100(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>D4 = 0;</code>
       */
      public static final int D4_VALUE = 0;
      /**
       * <code>D6 = 1;</code>
       */
      public static final int D6_VALUE = 1;
      /**
       * <code>D8 = 2;</code>
       */
      public static final int D8_VALUE = 2;
      /**
       * <code>D10 = 3;</code>
       */
      public static final int D10_VALUE = 3;
      /**
       * <code>D12 = 4;</code>
       */
      public static final int D12_VALUE = 4;
      /**
       * <code>D20 = 5;</code>
       */
      public static final int D20_VALUE = 5;
      /**
       * <code>D100 = 6;</code>
       */
      public static final int D100_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return D4;
          case 1: return D6;
          case 2: return D8;
          case 3: return D10;
          case 4: return D12;
          case 5: return D20;
          case 6: return D100;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return DiceOuterClass.DiceType.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DiceType.Type)
    }

    public static final int TIPODADO_FIELD_NUMBER = 1;
    private int tipoDado_;
    /**
     * <code>.DiceType.Type tipoDado = 1;</code>
     */
    public int getTipoDadoValue() {
      return tipoDado_;
    }
    /**
     * <code>.DiceType.Type tipoDado = 1;</code>
     */
    public DiceOuterClass.DiceType.Type getTipoDado() {
      DiceOuterClass.DiceType.Type result = DiceOuterClass.DiceType.Type.valueOf(tipoDado_);
      return result == null ? DiceOuterClass.DiceType.Type.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tipoDado_ != DiceOuterClass.DiceType.Type.D4.getNumber()) {
        output.writeEnum(1, tipoDado_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tipoDado_ != DiceOuterClass.DiceType.Type.D4.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, tipoDado_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DiceOuterClass.DiceType)) {
        return super.equals(obj);
      }
      DiceOuterClass.DiceType other = (DiceOuterClass.DiceType) obj;

      boolean result = true;
      result = result && tipoDado_ == other.tipoDado_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIPODADO_FIELD_NUMBER;
      hash = (53 * hash) + tipoDado_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DiceOuterClass.DiceType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DiceOuterClass.DiceType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DiceOuterClass.DiceType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DiceOuterClass.DiceType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DiceOuterClass.DiceType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DiceOuterClass.DiceType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DiceOuterClass.DiceType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DiceOuterClass.DiceType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DiceOuterClass.DiceType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DiceOuterClass.DiceType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DiceOuterClass.DiceType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DiceType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DiceType)
        DiceOuterClass.DiceTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DiceOuterClass.internal_static_DiceType_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DiceOuterClass.internal_static_DiceType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DiceOuterClass.DiceType.class, DiceOuterClass.DiceType.Builder.class);
      }

      // Construct using DiceOuterClass.DiceType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tipoDado_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DiceOuterClass.internal_static_DiceType_descriptor;
      }

      public DiceOuterClass.DiceType getDefaultInstanceForType() {
        return DiceOuterClass.DiceType.getDefaultInstance();
      }

      public DiceOuterClass.DiceType build() {
        DiceOuterClass.DiceType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DiceOuterClass.DiceType buildPartial() {
        DiceOuterClass.DiceType result = new DiceOuterClass.DiceType(this);
        result.tipoDado_ = tipoDado_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DiceOuterClass.DiceType) {
          return mergeFrom((DiceOuterClass.DiceType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DiceOuterClass.DiceType other) {
        if (other == DiceOuterClass.DiceType.getDefaultInstance()) return this;
        if (other.tipoDado_ != 0) {
          setTipoDadoValue(other.getTipoDadoValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DiceOuterClass.DiceType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DiceOuterClass.DiceType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int tipoDado_ = 0;
      /**
       * <code>.DiceType.Type tipoDado = 1;</code>
       */
      public int getTipoDadoValue() {
        return tipoDado_;
      }
      /**
       * <code>.DiceType.Type tipoDado = 1;</code>
       */
      public Builder setTipoDadoValue(int value) {
        tipoDado_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.DiceType.Type tipoDado = 1;</code>
       */
      public DiceOuterClass.DiceType.Type getTipoDado() {
        DiceOuterClass.DiceType.Type result = DiceOuterClass.DiceType.Type.valueOf(tipoDado_);
        return result == null ? DiceOuterClass.DiceType.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.DiceType.Type tipoDado = 1;</code>
       */
      public Builder setTipoDado(DiceOuterClass.DiceType.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        tipoDado_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.DiceType.Type tipoDado = 1;</code>
       */
      public Builder clearTipoDado() {
        
        tipoDado_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:DiceType)
    }

    // @@protoc_insertion_point(class_scope:DiceType)
    private static final DiceOuterClass.DiceType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DiceOuterClass.DiceType();
    }

    public static DiceOuterClass.DiceType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DiceType>
        PARSER = new com.google.protobuf.AbstractParser<DiceType>() {
      public DiceType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DiceType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DiceType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DiceType> getParserForType() {
      return PARSER;
    }

    public DiceOuterClass.DiceType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dice_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DiceType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DiceType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023messages/Dice.proto\"5\n\004Dice\022\024\n\014rolledN" +
      "umber\030\001 \001(\005\022\027\n\004type\030\002 \001(\0132\t.DiceType\"q\n\010" +
      "DiceType\022 \n\010tipoDado\030\001 \001(\0162\016.DiceType.Ty" +
      "pe\"C\n\004Type\022\006\n\002D4\020\000\022\006\n\002D6\020\001\022\006\n\002D8\020\002\022\007\n\003D1" +
      "0\020\003\022\007\n\003D12\020\004\022\007\n\003D20\020\005\022\010\n\004D100\020\006b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Dice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Dice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dice_descriptor,
        new java.lang.String[] { "RolledNumber", "Type", });
    internal_static_DiceType_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DiceType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DiceType_descriptor,
        new java.lang.String[] { "TipoDado", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
