package main.messages;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/Hero.proto

public final class HeroOuterClass {
  private HeroOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeroOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Hero)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 strength = 3;</code>
     */
    int getStrength();

    /**
     * <code>int32 resistance = 4;</code>
     */
    int getResistance();

    /**
     * <code>int32 maxHealth = 5;</code>
     */
    int getMaxHealth();

    /**
     * <code>int32 health = 6;</code>
     */
    int getHealth();
  }
  /**
   * Protobuf type {@code Hero}
   */
  public  static final class Hero extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Hero)
      HeroOrBuilder {
    // Use Hero.newBuilder() to construct.
    private Hero(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hero() {
      id_ = 0;
      name_ = "";
      strength_ = 0;
      resistance_ = 0;
      maxHealth_ = 0;
      health_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Hero(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              strength_ = input.readInt32();
              break;
            }
            case 32: {

              resistance_ = input.readInt32();
              break;
            }
            case 40: {

              maxHealth_ = input.readInt32();
              break;
            }
            case 48: {

              health_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeroOuterClass.internal_static_Hero_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeroOuterClass.internal_static_Hero_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeroOuterClass.Hero.class, HeroOuterClass.Hero.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRENGTH_FIELD_NUMBER = 3;
    private int strength_;
    /**
     * <code>int32 strength = 3;</code>
     */
    public int getStrength() {
      return strength_;
    }

    public static final int RESISTANCE_FIELD_NUMBER = 4;
    private int resistance_;
    /**
     * <code>int32 resistance = 4;</code>
     */
    public int getResistance() {
      return resistance_;
    }

    public static final int MAXHEALTH_FIELD_NUMBER = 5;
    private int maxHealth_;
    /**
     * <code>int32 maxHealth = 5;</code>
     */
    public int getMaxHealth() {
      return maxHealth_;
    }

    public static final int HEALTH_FIELD_NUMBER = 6;
    private int health_;
    /**
     * <code>int32 health = 6;</code>
     */
    public int getHealth() {
      return health_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (strength_ != 0) {
        output.writeInt32(3, strength_);
      }
      if (resistance_ != 0) {
        output.writeInt32(4, resistance_);
      }
      if (maxHealth_ != 0) {
        output.writeInt32(5, maxHealth_);
      }
      if (health_ != 0) {
        output.writeInt32(6, health_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (strength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, strength_);
      }
      if (resistance_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, resistance_);
      }
      if (maxHealth_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, maxHealth_);
      }
      if (health_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, health_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HeroOuterClass.Hero)) {
        return super.equals(obj);
      }
      HeroOuterClass.Hero other = (HeroOuterClass.Hero) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getStrength()
          == other.getStrength());
      result = result && (getResistance()
          == other.getResistance());
      result = result && (getMaxHealth()
          == other.getMaxHealth());
      result = result && (getHealth()
          == other.getHealth());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + STRENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getStrength();
      hash = (37 * hash) + RESISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getResistance();
      hash = (37 * hash) + MAXHEALTH_FIELD_NUMBER;
      hash = (53 * hash) + getMaxHealth();
      hash = (37 * hash) + HEALTH_FIELD_NUMBER;
      hash = (53 * hash) + getHealth();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HeroOuterClass.Hero parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeroOuterClass.Hero parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeroOuterClass.Hero parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeroOuterClass.Hero parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeroOuterClass.Hero parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeroOuterClass.Hero parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeroOuterClass.Hero parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HeroOuterClass.Hero parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeroOuterClass.Hero parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeroOuterClass.Hero parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HeroOuterClass.Hero prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Hero}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Hero)
        HeroOuterClass.HeroOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeroOuterClass.internal_static_Hero_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeroOuterClass.internal_static_Hero_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeroOuterClass.Hero.class, HeroOuterClass.Hero.Builder.class);
      }

      // Construct using HeroOuterClass.Hero.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        strength_ = 0;

        resistance_ = 0;

        maxHealth_ = 0;

        health_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeroOuterClass.internal_static_Hero_descriptor;
      }

      public HeroOuterClass.Hero getDefaultInstanceForType() {
        return HeroOuterClass.Hero.getDefaultInstance();
      }

      public HeroOuterClass.Hero build() {
        HeroOuterClass.Hero result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HeroOuterClass.Hero buildPartial() {
        HeroOuterClass.Hero result = new HeroOuterClass.Hero(this);
        result.id_ = id_;
        result.name_ = name_;
        result.strength_ = strength_;
        result.resistance_ = resistance_;
        result.maxHealth_ = maxHealth_;
        result.health_ = health_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeroOuterClass.Hero) {
          return mergeFrom((HeroOuterClass.Hero)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeroOuterClass.Hero other) {
        if (other == HeroOuterClass.Hero.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getStrength() != 0) {
          setStrength(other.getStrength());
        }
        if (other.getResistance() != 0) {
          setResistance(other.getResistance());
        }
        if (other.getMaxHealth() != 0) {
          setMaxHealth(other.getMaxHealth());
        }
        if (other.getHealth() != 0) {
          setHealth(other.getHealth());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeroOuterClass.Hero parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeroOuterClass.Hero) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int strength_ ;
      /**
       * <code>int32 strength = 3;</code>
       */
      public int getStrength() {
        return strength_;
      }
      /**
       * <code>int32 strength = 3;</code>
       */
      public Builder setStrength(int value) {
        
        strength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 strength = 3;</code>
       */
      public Builder clearStrength() {
        
        strength_ = 0;
        onChanged();
        return this;
      }

      private int resistance_ ;
      /**
       * <code>int32 resistance = 4;</code>
       */
      public int getResistance() {
        return resistance_;
      }
      /**
       * <code>int32 resistance = 4;</code>
       */
      public Builder setResistance(int value) {
        
        resistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 resistance = 4;</code>
       */
      public Builder clearResistance() {
        
        resistance_ = 0;
        onChanged();
        return this;
      }

      private int maxHealth_ ;
      /**
       * <code>int32 maxHealth = 5;</code>
       */
      public int getMaxHealth() {
        return maxHealth_;
      }
      /**
       * <code>int32 maxHealth = 5;</code>
       */
      public Builder setMaxHealth(int value) {
        
        maxHealth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 maxHealth = 5;</code>
       */
      public Builder clearMaxHealth() {
        
        maxHealth_ = 0;
        onChanged();
        return this;
      }

      private int health_ ;
      /**
       * <code>int32 health = 6;</code>
       */
      public int getHealth() {
        return health_;
      }
      /**
       * <code>int32 health = 6;</code>
       */
      public Builder setHealth(int value) {
        
        health_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 health = 6;</code>
       */
      public Builder clearHealth() {
        
        health_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Hero)
    }

    // @@protoc_insertion_point(class_scope:Hero)
    private static final HeroOuterClass.Hero DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HeroOuterClass.Hero();
    }

    public static HeroOuterClass.Hero getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Hero>
        PARSER = new com.google.protobuf.AbstractParser<Hero>() {
      public Hero parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Hero(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hero> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hero> getParserForType() {
      return PARSER;
    }

    public HeroOuterClass.Hero getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeroIDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeroID)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code HeroID}
   */
  public  static final class HeroID extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeroID)
      HeroIDOrBuilder {
    // Use HeroID.newBuilder() to construct.
    private HeroID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeroID() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HeroID(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeroOuterClass.internal_static_HeroID_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeroOuterClass.internal_static_HeroID_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeroOuterClass.HeroID.class, HeroOuterClass.HeroID.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HeroOuterClass.HeroID)) {
        return super.equals(obj);
      }
      HeroOuterClass.HeroID other = (HeroOuterClass.HeroID) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HeroOuterClass.HeroID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeroOuterClass.HeroID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeroOuterClass.HeroID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeroOuterClass.HeroID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeroOuterClass.HeroID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeroOuterClass.HeroID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeroOuterClass.HeroID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HeroOuterClass.HeroID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeroOuterClass.HeroID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeroOuterClass.HeroID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HeroOuterClass.HeroID prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeroID}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeroID)
        HeroOuterClass.HeroIDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeroOuterClass.internal_static_HeroID_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeroOuterClass.internal_static_HeroID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeroOuterClass.HeroID.class, HeroOuterClass.HeroID.Builder.class);
      }

      // Construct using HeroOuterClass.HeroID.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeroOuterClass.internal_static_HeroID_descriptor;
      }

      public HeroOuterClass.HeroID getDefaultInstanceForType() {
        return HeroOuterClass.HeroID.getDefaultInstance();
      }

      public HeroOuterClass.HeroID build() {
        HeroOuterClass.HeroID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HeroOuterClass.HeroID buildPartial() {
        HeroOuterClass.HeroID result = new HeroOuterClass.HeroID(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeroOuterClass.HeroID) {
          return mergeFrom((HeroOuterClass.HeroID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeroOuterClass.HeroID other) {
        if (other == HeroOuterClass.HeroID.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeroOuterClass.HeroID parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeroOuterClass.HeroID) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:HeroID)
    }

    // @@protoc_insertion_point(class_scope:HeroID)
    private static final HeroOuterClass.HeroID DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HeroOuterClass.HeroID();
    }

    public static HeroOuterClass.HeroID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeroID>
        PARSER = new com.google.protobuf.AbstractParser<HeroID>() {
      public HeroID parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeroID(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeroID> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeroID> getParserForType() {
      return PARSER;
    }

    public HeroOuterClass.HeroID getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeroesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Heroes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Hero hero = 1;</code>
     */
    java.util.List<HeroOuterClass.Hero> 
        getHeroList();
    /**
     * <code>repeated .Hero hero = 1;</code>
     */
    HeroOuterClass.Hero getHero(int index);
    /**
     * <code>repeated .Hero hero = 1;</code>
     */
    int getHeroCount();
    /**
     * <code>repeated .Hero hero = 1;</code>
     */
    java.util.List<? extends HeroOuterClass.HeroOrBuilder> 
        getHeroOrBuilderList();
    /**
     * <code>repeated .Hero hero = 1;</code>
     */
    HeroOuterClass.HeroOrBuilder getHeroOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Heroes}
   */
  public  static final class Heroes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Heroes)
      HeroesOrBuilder {
    // Use Heroes.newBuilder() to construct.
    private Heroes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Heroes() {
      hero_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Heroes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                hero_ = new java.util.ArrayList<HeroOuterClass.Hero>();
                mutable_bitField0_ |= 0x00000001;
              }
              hero_.add(
                  input.readMessage(HeroOuterClass.Hero.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          hero_ = java.util.Collections.unmodifiableList(hero_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeroOuterClass.internal_static_Heroes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeroOuterClass.internal_static_Heroes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeroOuterClass.Heroes.class, HeroOuterClass.Heroes.Builder.class);
    }

    public static final int HERO_FIELD_NUMBER = 1;
    private java.util.List<HeroOuterClass.Hero> hero_;
    /**
     * <code>repeated .Hero hero = 1;</code>
     */
    public java.util.List<HeroOuterClass.Hero> getHeroList() {
      return hero_;
    }
    /**
     * <code>repeated .Hero hero = 1;</code>
     */
    public java.util.List<? extends HeroOuterClass.HeroOrBuilder> 
        getHeroOrBuilderList() {
      return hero_;
    }
    /**
     * <code>repeated .Hero hero = 1;</code>
     */
    public int getHeroCount() {
      return hero_.size();
    }
    /**
     * <code>repeated .Hero hero = 1;</code>
     */
    public HeroOuterClass.Hero getHero(int index) {
      return hero_.get(index);
    }
    /**
     * <code>repeated .Hero hero = 1;</code>
     */
    public HeroOuterClass.HeroOrBuilder getHeroOrBuilder(
        int index) {
      return hero_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < hero_.size(); i++) {
        output.writeMessage(1, hero_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < hero_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, hero_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HeroOuterClass.Heroes)) {
        return super.equals(obj);
      }
      HeroOuterClass.Heroes other = (HeroOuterClass.Heroes) obj;

      boolean result = true;
      result = result && getHeroList()
          .equals(other.getHeroList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHeroCount() > 0) {
        hash = (37 * hash) + HERO_FIELD_NUMBER;
        hash = (53 * hash) + getHeroList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HeroOuterClass.Heroes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeroOuterClass.Heroes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeroOuterClass.Heroes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeroOuterClass.Heroes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeroOuterClass.Heroes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeroOuterClass.Heroes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeroOuterClass.Heroes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HeroOuterClass.Heroes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeroOuterClass.Heroes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeroOuterClass.Heroes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HeroOuterClass.Heroes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Heroes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Heroes)
        HeroOuterClass.HeroesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeroOuterClass.internal_static_Heroes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeroOuterClass.internal_static_Heroes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeroOuterClass.Heroes.class, HeroOuterClass.Heroes.Builder.class);
      }

      // Construct using HeroOuterClass.Heroes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeroFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (heroBuilder_ == null) {
          hero_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          heroBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeroOuterClass.internal_static_Heroes_descriptor;
      }

      public HeroOuterClass.Heroes getDefaultInstanceForType() {
        return HeroOuterClass.Heroes.getDefaultInstance();
      }

      public HeroOuterClass.Heroes build() {
        HeroOuterClass.Heroes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HeroOuterClass.Heroes buildPartial() {
        HeroOuterClass.Heroes result = new HeroOuterClass.Heroes(this);
        int from_bitField0_ = bitField0_;
        if (heroBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            hero_ = java.util.Collections.unmodifiableList(hero_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.hero_ = hero_;
        } else {
          result.hero_ = heroBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeroOuterClass.Heroes) {
          return mergeFrom((HeroOuterClass.Heroes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeroOuterClass.Heroes other) {
        if (other == HeroOuterClass.Heroes.getDefaultInstance()) return this;
        if (heroBuilder_ == null) {
          if (!other.hero_.isEmpty()) {
            if (hero_.isEmpty()) {
              hero_ = other.hero_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHeroIsMutable();
              hero_.addAll(other.hero_);
            }
            onChanged();
          }
        } else {
          if (!other.hero_.isEmpty()) {
            if (heroBuilder_.isEmpty()) {
              heroBuilder_.dispose();
              heroBuilder_ = null;
              hero_ = other.hero_;
              bitField0_ = (bitField0_ & ~0x00000001);
              heroBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHeroFieldBuilder() : null;
            } else {
              heroBuilder_.addAllMessages(other.hero_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeroOuterClass.Heroes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeroOuterClass.Heroes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<HeroOuterClass.Hero> hero_ =
        java.util.Collections.emptyList();
      private void ensureHeroIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          hero_ = new java.util.ArrayList<HeroOuterClass.Hero>(hero_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          HeroOuterClass.Hero, HeroOuterClass.Hero.Builder, HeroOuterClass.HeroOrBuilder> heroBuilder_;

      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public java.util.List<HeroOuterClass.Hero> getHeroList() {
        if (heroBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hero_);
        } else {
          return heroBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public int getHeroCount() {
        if (heroBuilder_ == null) {
          return hero_.size();
        } else {
          return heroBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public HeroOuterClass.Hero getHero(int index) {
        if (heroBuilder_ == null) {
          return hero_.get(index);
        } else {
          return heroBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public Builder setHero(
          int index, HeroOuterClass.Hero value) {
        if (heroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroIsMutable();
          hero_.set(index, value);
          onChanged();
        } else {
          heroBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public Builder setHero(
          int index, HeroOuterClass.Hero.Builder builderForValue) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          hero_.set(index, builderForValue.build());
          onChanged();
        } else {
          heroBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public Builder addHero(HeroOuterClass.Hero value) {
        if (heroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroIsMutable();
          hero_.add(value);
          onChanged();
        } else {
          heroBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public Builder addHero(
          int index, HeroOuterClass.Hero value) {
        if (heroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroIsMutable();
          hero_.add(index, value);
          onChanged();
        } else {
          heroBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public Builder addHero(
          HeroOuterClass.Hero.Builder builderForValue) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          hero_.add(builderForValue.build());
          onChanged();
        } else {
          heroBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public Builder addHero(
          int index, HeroOuterClass.Hero.Builder builderForValue) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          hero_.add(index, builderForValue.build());
          onChanged();
        } else {
          heroBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public Builder addAllHero(
          java.lang.Iterable<? extends HeroOuterClass.Hero> values) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, hero_);
          onChanged();
        } else {
          heroBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public Builder clearHero() {
        if (heroBuilder_ == null) {
          hero_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          heroBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public Builder removeHero(int index) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          hero_.remove(index);
          onChanged();
        } else {
          heroBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public HeroOuterClass.Hero.Builder getHeroBuilder(
          int index) {
        return getHeroFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public HeroOuterClass.HeroOrBuilder getHeroOrBuilder(
          int index) {
        if (heroBuilder_ == null) {
          return hero_.get(index);  } else {
          return heroBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public java.util.List<? extends HeroOuterClass.HeroOrBuilder> 
           getHeroOrBuilderList() {
        if (heroBuilder_ != null) {
          return heroBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hero_);
        }
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public HeroOuterClass.Hero.Builder addHeroBuilder() {
        return getHeroFieldBuilder().addBuilder(
            HeroOuterClass.Hero.getDefaultInstance());
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public HeroOuterClass.Hero.Builder addHeroBuilder(
          int index) {
        return getHeroFieldBuilder().addBuilder(
            index, HeroOuterClass.Hero.getDefaultInstance());
      }
      /**
       * <code>repeated .Hero hero = 1;</code>
       */
      public java.util.List<HeroOuterClass.Hero.Builder> 
           getHeroBuilderList() {
        return getHeroFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          HeroOuterClass.Hero, HeroOuterClass.Hero.Builder, HeroOuterClass.HeroOrBuilder> 
          getHeroFieldBuilder() {
        if (heroBuilder_ == null) {
          heroBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              HeroOuterClass.Hero, HeroOuterClass.Hero.Builder, HeroOuterClass.HeroOrBuilder>(
                  hero_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          hero_ = null;
        }
        return heroBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Heroes)
    }

    // @@protoc_insertion_point(class_scope:Heroes)
    private static final HeroOuterClass.Heroes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HeroOuterClass.Heroes();
    }

    public static HeroOuterClass.Heroes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Heroes>
        PARSER = new com.google.protobuf.AbstractParser<Heroes>() {
      public Heroes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Heroes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Heroes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Heroes> getParserForType() {
      return PARSER;
    }

    public HeroOuterClass.Heroes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Hero_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Hero_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeroID_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeroID_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Heroes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Heroes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023messages/Hero.proto\"i\n\004Hero\022\n\n\002id\030\001 \001(" +
      "\005\022\014\n\004name\030\002 \001(\t\022\020\n\010strength\030\003 \001(\005\022\022\n\nres" +
      "istance\030\004 \001(\005\022\021\n\tmaxHealth\030\005 \001(\005\022\016\n\006heal" +
      "th\030\006 \001(\005\"\024\n\006HeroID\022\n\n\002id\030\001 \001(\005\"\035\n\006Heroes" +
      "\022\023\n\004hero\030\001 \003(\0132\005.Herob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Hero_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Hero_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Hero_descriptor,
        new java.lang.String[] { "Id", "Name", "Strength", "Resistance", "MaxHealth", "Health", });
    internal_static_HeroID_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeroID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeroID_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Heroes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Heroes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Heroes_descriptor,
        new java.lang.String[] { "Hero", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
