package main.messages;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/Monster.proto

public final class MonsterOuterClass {
  private MonsterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MonsterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Monster)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 strength = 3;</code>
     */
    int getStrength();

    /**
     * <code>int32 resistance = 4;</code>
     */
    int getResistance();

    /**
     * <code>int32 health = 5;</code>
     */
    int getHealth();
  }
  /**
   * Protobuf type {@code Monster}
   */
  public  static final class Monster extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Monster)
      MonsterOrBuilder {
    // Use Monster.newBuilder() to construct.
    private Monster(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Monster() {
      id_ = 0;
      name_ = "";
      strength_ = 0;
      resistance_ = 0;
      health_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Monster(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              strength_ = input.readInt32();
              break;
            }
            case 32: {

              resistance_ = input.readInt32();
              break;
            }
            case 40: {

              health_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MonsterOuterClass.internal_static_Monster_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MonsterOuterClass.internal_static_Monster_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MonsterOuterClass.Monster.class, MonsterOuterClass.Monster.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRENGTH_FIELD_NUMBER = 3;
    private int strength_;
    /**
     * <code>int32 strength = 3;</code>
     */
    public int getStrength() {
      return strength_;
    }

    public static final int RESISTANCE_FIELD_NUMBER = 4;
    private int resistance_;
    /**
     * <code>int32 resistance = 4;</code>
     */
    public int getResistance() {
      return resistance_;
    }

    public static final int HEALTH_FIELD_NUMBER = 5;
    private int health_;
    /**
     * <code>int32 health = 5;</code>
     */
    public int getHealth() {
      return health_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (strength_ != 0) {
        output.writeInt32(3, strength_);
      }
      if (resistance_ != 0) {
        output.writeInt32(4, resistance_);
      }
      if (health_ != 0) {
        output.writeInt32(5, health_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (strength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, strength_);
      }
      if (resistance_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, resistance_);
      }
      if (health_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, health_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MonsterOuterClass.Monster)) {
        return super.equals(obj);
      }
      MonsterOuterClass.Monster other = (MonsterOuterClass.Monster) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getStrength()
          == other.getStrength());
      result = result && (getResistance()
          == other.getResistance());
      result = result && (getHealth()
          == other.getHealth());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + STRENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getStrength();
      hash = (37 * hash) + RESISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getResistance();
      hash = (37 * hash) + HEALTH_FIELD_NUMBER;
      hash = (53 * hash) + getHealth();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MonsterOuterClass.Monster parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MonsterOuterClass.Monster parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MonsterOuterClass.Monster parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MonsterOuterClass.Monster parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MonsterOuterClass.Monster parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MonsterOuterClass.Monster parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MonsterOuterClass.Monster parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MonsterOuterClass.Monster parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MonsterOuterClass.Monster parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MonsterOuterClass.Monster parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MonsterOuterClass.Monster prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Monster}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Monster)
        MonsterOuterClass.MonsterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MonsterOuterClass.internal_static_Monster_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MonsterOuterClass.internal_static_Monster_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MonsterOuterClass.Monster.class, MonsterOuterClass.Monster.Builder.class);
      }

      // Construct using MonsterOuterClass.Monster.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        strength_ = 0;

        resistance_ = 0;

        health_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MonsterOuterClass.internal_static_Monster_descriptor;
      }

      public MonsterOuterClass.Monster getDefaultInstanceForType() {
        return MonsterOuterClass.Monster.getDefaultInstance();
      }

      public MonsterOuterClass.Monster build() {
        MonsterOuterClass.Monster result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MonsterOuterClass.Monster buildPartial() {
        MonsterOuterClass.Monster result = new MonsterOuterClass.Monster(this);
        result.id_ = id_;
        result.name_ = name_;
        result.strength_ = strength_;
        result.resistance_ = resistance_;
        result.health_ = health_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MonsterOuterClass.Monster) {
          return mergeFrom((MonsterOuterClass.Monster)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MonsterOuterClass.Monster other) {
        if (other == MonsterOuterClass.Monster.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getStrength() != 0) {
          setStrength(other.getStrength());
        }
        if (other.getResistance() != 0) {
          setResistance(other.getResistance());
        }
        if (other.getHealth() != 0) {
          setHealth(other.getHealth());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MonsterOuterClass.Monster parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MonsterOuterClass.Monster) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int strength_ ;
      /**
       * <code>int32 strength = 3;</code>
       */
      public int getStrength() {
        return strength_;
      }
      /**
       * <code>int32 strength = 3;</code>
       */
      public Builder setStrength(int value) {
        
        strength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 strength = 3;</code>
       */
      public Builder clearStrength() {
        
        strength_ = 0;
        onChanged();
        return this;
      }

      private int resistance_ ;
      /**
       * <code>int32 resistance = 4;</code>
       */
      public int getResistance() {
        return resistance_;
      }
      /**
       * <code>int32 resistance = 4;</code>
       */
      public Builder setResistance(int value) {
        
        resistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 resistance = 4;</code>
       */
      public Builder clearResistance() {
        
        resistance_ = 0;
        onChanged();
        return this;
      }

      private int health_ ;
      /**
       * <code>int32 health = 5;</code>
       */
      public int getHealth() {
        return health_;
      }
      /**
       * <code>int32 health = 5;</code>
       */
      public Builder setHealth(int value) {
        
        health_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 health = 5;</code>
       */
      public Builder clearHealth() {
        
        health_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Monster)
    }

    // @@protoc_insertion_point(class_scope:Monster)
    private static final MonsterOuterClass.Monster DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MonsterOuterClass.Monster();
    }

    public static MonsterOuterClass.Monster getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Monster>
        PARSER = new com.google.protobuf.AbstractParser<Monster>() {
      public Monster parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Monster(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Monster> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Monster> getParserForType() {
      return PARSER;
    }

    public MonsterOuterClass.Monster getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MonsterQtOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MonsterQt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 qt = 1;</code>
     */
    int getQt();
  }
  /**
   * Protobuf type {@code MonsterQt}
   */
  public  static final class MonsterQt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MonsterQt)
      MonsterQtOrBuilder {
    // Use MonsterQt.newBuilder() to construct.
    private MonsterQt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MonsterQt() {
      qt_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MonsterQt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              qt_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MonsterOuterClass.internal_static_MonsterQt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MonsterOuterClass.internal_static_MonsterQt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MonsterOuterClass.MonsterQt.class, MonsterOuterClass.MonsterQt.Builder.class);
    }

    public static final int QT_FIELD_NUMBER = 1;
    private int qt_;
    /**
     * <code>int32 qt = 1;</code>
     */
    public int getQt() {
      return qt_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (qt_ != 0) {
        output.writeInt32(1, qt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (qt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, qt_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MonsterOuterClass.MonsterQt)) {
        return super.equals(obj);
      }
      MonsterOuterClass.MonsterQt other = (MonsterOuterClass.MonsterQt) obj;

      boolean result = true;
      result = result && (getQt()
          == other.getQt());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QT_FIELD_NUMBER;
      hash = (53 * hash) + getQt();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MonsterOuterClass.MonsterQt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MonsterOuterClass.MonsterQt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MonsterOuterClass.MonsterQt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MonsterOuterClass.MonsterQt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MonsterOuterClass.MonsterQt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MonsterOuterClass.MonsterQt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MonsterOuterClass.MonsterQt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MonsterOuterClass.MonsterQt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MonsterOuterClass.MonsterQt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MonsterOuterClass.MonsterQt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MonsterOuterClass.MonsterQt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MonsterQt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MonsterQt)
        MonsterOuterClass.MonsterQtOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MonsterOuterClass.internal_static_MonsterQt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MonsterOuterClass.internal_static_MonsterQt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MonsterOuterClass.MonsterQt.class, MonsterOuterClass.MonsterQt.Builder.class);
      }

      // Construct using MonsterOuterClass.MonsterQt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        qt_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MonsterOuterClass.internal_static_MonsterQt_descriptor;
      }

      public MonsterOuterClass.MonsterQt getDefaultInstanceForType() {
        return MonsterOuterClass.MonsterQt.getDefaultInstance();
      }

      public MonsterOuterClass.MonsterQt build() {
        MonsterOuterClass.MonsterQt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MonsterOuterClass.MonsterQt buildPartial() {
        MonsterOuterClass.MonsterQt result = new MonsterOuterClass.MonsterQt(this);
        result.qt_ = qt_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MonsterOuterClass.MonsterQt) {
          return mergeFrom((MonsterOuterClass.MonsterQt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MonsterOuterClass.MonsterQt other) {
        if (other == MonsterOuterClass.MonsterQt.getDefaultInstance()) return this;
        if (other.getQt() != 0) {
          setQt(other.getQt());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MonsterOuterClass.MonsterQt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MonsterOuterClass.MonsterQt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int qt_ ;
      /**
       * <code>int32 qt = 1;</code>
       */
      public int getQt() {
        return qt_;
      }
      /**
       * <code>int32 qt = 1;</code>
       */
      public Builder setQt(int value) {
        
        qt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 qt = 1;</code>
       */
      public Builder clearQt() {
        
        qt_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:MonsterQt)
    }

    // @@protoc_insertion_point(class_scope:MonsterQt)
    private static final MonsterOuterClass.MonsterQt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MonsterOuterClass.MonsterQt();
    }

    public static MonsterOuterClass.MonsterQt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MonsterQt>
        PARSER = new com.google.protobuf.AbstractParser<MonsterQt>() {
      public MonsterQt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MonsterQt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MonsterQt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MonsterQt> getParserForType() {
      return PARSER;
    }

    public MonsterOuterClass.MonsterQt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MonstersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Monsters)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Monster monster = 1;</code>
     */
    java.util.List<MonsterOuterClass.Monster> 
        getMonsterList();
    /**
     * <code>repeated .Monster monster = 1;</code>
     */
    MonsterOuterClass.Monster getMonster(int index);
    /**
     * <code>repeated .Monster monster = 1;</code>
     */
    int getMonsterCount();
    /**
     * <code>repeated .Monster monster = 1;</code>
     */
    java.util.List<? extends MonsterOuterClass.MonsterOrBuilder> 
        getMonsterOrBuilderList();
    /**
     * <code>repeated .Monster monster = 1;</code>
     */
    MonsterOuterClass.MonsterOrBuilder getMonsterOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Monsters}
   */
  public  static final class Monsters extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Monsters)
      MonstersOrBuilder {
    // Use Monsters.newBuilder() to construct.
    private Monsters(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Monsters() {
      monster_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Monsters(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                monster_ = new java.util.ArrayList<MonsterOuterClass.Monster>();
                mutable_bitField0_ |= 0x00000001;
              }
              monster_.add(
                  input.readMessage(MonsterOuterClass.Monster.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          monster_ = java.util.Collections.unmodifiableList(monster_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MonsterOuterClass.internal_static_Monsters_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MonsterOuterClass.internal_static_Monsters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MonsterOuterClass.Monsters.class, MonsterOuterClass.Monsters.Builder.class);
    }

    public static final int MONSTER_FIELD_NUMBER = 1;
    private java.util.List<MonsterOuterClass.Monster> monster_;
    /**
     * <code>repeated .Monster monster = 1;</code>
     */
    public java.util.List<MonsterOuterClass.Monster> getMonsterList() {
      return monster_;
    }
    /**
     * <code>repeated .Monster monster = 1;</code>
     */
    public java.util.List<? extends MonsterOuterClass.MonsterOrBuilder> 
        getMonsterOrBuilderList() {
      return monster_;
    }
    /**
     * <code>repeated .Monster monster = 1;</code>
     */
    public int getMonsterCount() {
      return monster_.size();
    }
    /**
     * <code>repeated .Monster monster = 1;</code>
     */
    public MonsterOuterClass.Monster getMonster(int index) {
      return monster_.get(index);
    }
    /**
     * <code>repeated .Monster monster = 1;</code>
     */
    public MonsterOuterClass.MonsterOrBuilder getMonsterOrBuilder(
        int index) {
      return monster_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < monster_.size(); i++) {
        output.writeMessage(1, monster_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < monster_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, monster_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MonsterOuterClass.Monsters)) {
        return super.equals(obj);
      }
      MonsterOuterClass.Monsters other = (MonsterOuterClass.Monsters) obj;

      boolean result = true;
      result = result && getMonsterList()
          .equals(other.getMonsterList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMonsterCount() > 0) {
        hash = (37 * hash) + MONSTER_FIELD_NUMBER;
        hash = (53 * hash) + getMonsterList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MonsterOuterClass.Monsters parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MonsterOuterClass.Monsters parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MonsterOuterClass.Monsters parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MonsterOuterClass.Monsters parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MonsterOuterClass.Monsters parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MonsterOuterClass.Monsters parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MonsterOuterClass.Monsters parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MonsterOuterClass.Monsters parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MonsterOuterClass.Monsters parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MonsterOuterClass.Monsters parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MonsterOuterClass.Monsters prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Monsters}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Monsters)
        MonsterOuterClass.MonstersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MonsterOuterClass.internal_static_Monsters_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MonsterOuterClass.internal_static_Monsters_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MonsterOuterClass.Monsters.class, MonsterOuterClass.Monsters.Builder.class);
      }

      // Construct using MonsterOuterClass.Monsters.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMonsterFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (monsterBuilder_ == null) {
          monster_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          monsterBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MonsterOuterClass.internal_static_Monsters_descriptor;
      }

      public MonsterOuterClass.Monsters getDefaultInstanceForType() {
        return MonsterOuterClass.Monsters.getDefaultInstance();
      }

      public MonsterOuterClass.Monsters build() {
        MonsterOuterClass.Monsters result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MonsterOuterClass.Monsters buildPartial() {
        MonsterOuterClass.Monsters result = new MonsterOuterClass.Monsters(this);
        int from_bitField0_ = bitField0_;
        if (monsterBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            monster_ = java.util.Collections.unmodifiableList(monster_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.monster_ = monster_;
        } else {
          result.monster_ = monsterBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MonsterOuterClass.Monsters) {
          return mergeFrom((MonsterOuterClass.Monsters)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MonsterOuterClass.Monsters other) {
        if (other == MonsterOuterClass.Monsters.getDefaultInstance()) return this;
        if (monsterBuilder_ == null) {
          if (!other.monster_.isEmpty()) {
            if (monster_.isEmpty()) {
              monster_ = other.monster_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMonsterIsMutable();
              monster_.addAll(other.monster_);
            }
            onChanged();
          }
        } else {
          if (!other.monster_.isEmpty()) {
            if (monsterBuilder_.isEmpty()) {
              monsterBuilder_.dispose();
              monsterBuilder_ = null;
              monster_ = other.monster_;
              bitField0_ = (bitField0_ & ~0x00000001);
              monsterBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMonsterFieldBuilder() : null;
            } else {
              monsterBuilder_.addAllMessages(other.monster_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MonsterOuterClass.Monsters parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MonsterOuterClass.Monsters) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<MonsterOuterClass.Monster> monster_ =
        java.util.Collections.emptyList();
      private void ensureMonsterIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          monster_ = new java.util.ArrayList<MonsterOuterClass.Monster>(monster_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MonsterOuterClass.Monster, MonsterOuterClass.Monster.Builder, MonsterOuterClass.MonsterOrBuilder> monsterBuilder_;

      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public java.util.List<MonsterOuterClass.Monster> getMonsterList() {
        if (monsterBuilder_ == null) {
          return java.util.Collections.unmodifiableList(monster_);
        } else {
          return monsterBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public int getMonsterCount() {
        if (monsterBuilder_ == null) {
          return monster_.size();
        } else {
          return monsterBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public MonsterOuterClass.Monster getMonster(int index) {
        if (monsterBuilder_ == null) {
          return monster_.get(index);
        } else {
          return monsterBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public Builder setMonster(
          int index, MonsterOuterClass.Monster value) {
        if (monsterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonsterIsMutable();
          monster_.set(index, value);
          onChanged();
        } else {
          monsterBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public Builder setMonster(
          int index, MonsterOuterClass.Monster.Builder builderForValue) {
        if (monsterBuilder_ == null) {
          ensureMonsterIsMutable();
          monster_.set(index, builderForValue.build());
          onChanged();
        } else {
          monsterBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public Builder addMonster(MonsterOuterClass.Monster value) {
        if (monsterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonsterIsMutable();
          monster_.add(value);
          onChanged();
        } else {
          monsterBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public Builder addMonster(
          int index, MonsterOuterClass.Monster value) {
        if (monsterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonsterIsMutable();
          monster_.add(index, value);
          onChanged();
        } else {
          monsterBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public Builder addMonster(
          MonsterOuterClass.Monster.Builder builderForValue) {
        if (monsterBuilder_ == null) {
          ensureMonsterIsMutable();
          monster_.add(builderForValue.build());
          onChanged();
        } else {
          monsterBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public Builder addMonster(
          int index, MonsterOuterClass.Monster.Builder builderForValue) {
        if (monsterBuilder_ == null) {
          ensureMonsterIsMutable();
          monster_.add(index, builderForValue.build());
          onChanged();
        } else {
          monsterBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public Builder addAllMonster(
          java.lang.Iterable<? extends MonsterOuterClass.Monster> values) {
        if (monsterBuilder_ == null) {
          ensureMonsterIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, monster_);
          onChanged();
        } else {
          monsterBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public Builder clearMonster() {
        if (monsterBuilder_ == null) {
          monster_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          monsterBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public Builder removeMonster(int index) {
        if (monsterBuilder_ == null) {
          ensureMonsterIsMutable();
          monster_.remove(index);
          onChanged();
        } else {
          monsterBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public MonsterOuterClass.Monster.Builder getMonsterBuilder(
          int index) {
        return getMonsterFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public MonsterOuterClass.MonsterOrBuilder getMonsterOrBuilder(
          int index) {
        if (monsterBuilder_ == null) {
          return monster_.get(index);  } else {
          return monsterBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public java.util.List<? extends MonsterOuterClass.MonsterOrBuilder> 
           getMonsterOrBuilderList() {
        if (monsterBuilder_ != null) {
          return monsterBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(monster_);
        }
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public MonsterOuterClass.Monster.Builder addMonsterBuilder() {
        return getMonsterFieldBuilder().addBuilder(
            MonsterOuterClass.Monster.getDefaultInstance());
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public MonsterOuterClass.Monster.Builder addMonsterBuilder(
          int index) {
        return getMonsterFieldBuilder().addBuilder(
            index, MonsterOuterClass.Monster.getDefaultInstance());
      }
      /**
       * <code>repeated .Monster monster = 1;</code>
       */
      public java.util.List<MonsterOuterClass.Monster.Builder> 
           getMonsterBuilderList() {
        return getMonsterFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MonsterOuterClass.Monster, MonsterOuterClass.Monster.Builder, MonsterOuterClass.MonsterOrBuilder> 
          getMonsterFieldBuilder() {
        if (monsterBuilder_ == null) {
          monsterBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MonsterOuterClass.Monster, MonsterOuterClass.Monster.Builder, MonsterOuterClass.MonsterOrBuilder>(
                  monster_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          monster_ = null;
        }
        return monsterBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Monsters)
    }

    // @@protoc_insertion_point(class_scope:Monsters)
    private static final MonsterOuterClass.Monsters DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MonsterOuterClass.Monsters();
    }

    public static MonsterOuterClass.Monsters getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Monsters>
        PARSER = new com.google.protobuf.AbstractParser<Monsters>() {
      public Monsters parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Monsters(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Monsters> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Monsters> getParserForType() {
      return PARSER;
    }

    public MonsterOuterClass.Monsters getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Monster_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Monster_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MonsterQt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MonsterQt_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Monsters_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Monsters_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026messages/Monster.proto\"Y\n\007Monster\022\n\n\002i" +
      "d\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010strength\030\003 \001(\005\022" +
      "\022\n\nresistance\030\004 \001(\005\022\016\n\006health\030\005 \001(\005\"\027\n\tM" +
      "onsterQt\022\n\n\002qt\030\001 \001(\005\"%\n\010Monsters\022\031\n\007mons" +
      "ter\030\001 \003(\0132\010.Monsterb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Monster_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Monster_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Monster_descriptor,
        new java.lang.String[] { "Id", "Name", "Strength", "Resistance", "Health", });
    internal_static_MonsterQt_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MonsterQt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MonsterQt_descriptor,
        new java.lang.String[] { "Qt", });
    internal_static_Monsters_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Monsters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Monsters_descriptor,
        new java.lang.String[] { "Monster", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
